gen_sql="""你是一名专业 BI 数据分析师,使用以下上下文作为你所学习的知识，放在<context></context>XML标签内
<context>
{knowledge}
</context>
用户的问题将只会聚焦于统计SQL语句的生成和统计图表建议，SQL 语句基于 MySQL8.0语法。
当回答用户时：
1. 如果信息不够，无法生成可直接运行的 SQL，则提示用户需要补充什么内容, 提示语整体包裹在<hint></hint>XML标签内
2. 回答中只能包含一条 SQL 语句以及统计图表推荐，并返回《统计图表文档》中的序号（必须以“图表编号:n“这种格式进行回复, n表示 《统计图表文档》中的图表编号），如果是 SQL 结果是单行单列等简单数据，则选择 无需图表
3. 不要生成多条SQL，如果因为信息不明确，无法生成唯一的一条 SQL，则要求用户对可能需求做选择或额外补充信息，提示语整体包裹在<hint></hint>XML标签内
3. 生成的 SQL 的列名展示为用户可理解的概念术语而非数据库字段
4. 生成的 SQL 语句有 group by 时，不能违反 ONLY_FULL_GROUP_BY
5. 如果使用到窗口函数 LAG，则要注意处理 NULL 值，避免除零的错误
6. MySQL 中列别名若包含空格或特殊字符，必须使用反引号（`）包裹，单引号会被识别为字符串常量，导致语法错误。
7. 所有表中可能存在 is_deleted字段，所有的语句生成都要包含 is_deleted = 0 的条件，过滤掉已删除的数据
"""


intention="""你是一个知识库，使用以下上下文作为你所学习的知识，放在<context></context>XML标签内
<context>
{knowledge}
</context>

用户提问后，分析用户的意图以及现有知识是否可以直接回答：
1. 如果需要统计数据才能回答，则输出 "<analysis>需要SQL<analysis>"
2. 如果可以直接根据知识回答，则不要输出任何  "<analysis>需要SQL<analysis>" 
3. 你只需要做用途的意图分析和知识的总结，不做任何生成 SQL 的事情
"""

ddl_sql="""
DROP TABLE IF EXISTS `blade_dept_0227_to_li`;
CREATE TABLE `blade_dept_0227_to_li`  (
  `id` bigint(64) NOT NULL COMMENT '主键',
  `tenant_id` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '000000' COMMENT '租户ID',
  `parent_id` bigint(64) NULL DEFAULT 0 COMMENT '父主键',
  `ancestors` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '祖级列表',
  `dept_category` int(2) NULL DEFAULT NULL COMMENT '部门类型',
  `dept_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '部门名',
  `full_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '部门全称',
  `sort` int(11) NULL DEFAULT NULL COMMENT '排序',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '机构表' ROW_FORMAT = Dynamic;


DROP TABLE IF EXISTS `evaluation_0227_to_li`;
CREATE TABLE `evaluation_0227_to_li`  (
  `id` bigint(20) NOT NULL COMMENT '定检id',
  `regular_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '定检单元id',
  `highway_segment_id` bigint(20) NULL DEFAULT NULL COMMENT '路段id',
  `highway_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线类型（字典：1 主线；2 匝道；3 其他）',
  `interchange_id` bigint(20) NULL DEFAULT NULL COMMENT '互通id',
  `ramp_id` bigint(20) NULL DEFAULT NULL COMMENT '匝道id',
  `highway_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '路线编码',
  `highway_segment_simple_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路段简称',
  `check_year` date NULL DEFAULT NULL COMMENT '检测时间',
  `evaluation_unit` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '评价单元(字典：1 千米；2 百米)',
  `direction` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '行车方向（字典：11 上行；12 下行； 20双向）',
  `roadway` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '车道（字典：1 1车道；2 2车道；3 3车道；4 4车道；5 5车道）',
  `start_pile_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '起点桩号名称',
  `start_pile_code` decimal(20, 3) NULL DEFAULT NULL COMMENT '起点桩号编号',
  `start_pile_unit` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '起点桩号单位',
  `end_pile_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '终点桩号名称',
  `end_pile_code` decimal(20, 3) NULL DEFAULT NULL COMMENT '终点桩号编号',
  `end_pile_unit` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '终点桩号单位',
  `center_pile_code` decimal(20, 3) NULL DEFAULT NULL COMMENT '中心桩号编号',
  `check_length` int(20) NULL DEFAULT NULL COMMENT '单元长度',
  `bilateral_pqi` decimal(20, 2) NULL DEFAULT NULL COMMENT '双侧PQI',
  `pqi` decimal(20, 2) NULL DEFAULT NULL COMMENT '右侧PQI',
  `pci` decimal(20, 2) NULL DEFAULT NULL COMMENT 'PCI',
  `rdi` decimal(20, 2) NULL DEFAULT NULL COMMENT 'RDI',
  `bilateral_rqi` decimal(20, 2) NULL DEFAULT NULL COMMENT '双侧RQI',
  `rqi` decimal(20, 2) NULL DEFAULT NULL COMMENT '右侧RQI',
  `pbi` decimal(20, 2) NULL DEFAULT NULL COMMENT 'PBI',
  `pwi` decimal(20, 2) NULL DEFAULT NULL COMMENT 'PWI',
  `pqi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PQI国标评定',
  `pci_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PCI国标评定',
  `rdi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'RDI国标评定',
  `rqi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'RQI国标评定',
  `pbi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PBI国标评定',
  `pwi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PWI国标评定',
  `sri_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'SRI国标评定',
  `pssi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PSSI国标评定',
  `all_right_rqi_standard` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '全指标(右侧RQI达标)',
  `whole_bilateral_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '全指标（双侧RQI）省标评定',
  `bilateral_rqi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'RQI国标评定',
  `sri` decimal(20, 2) NULL DEFAULT NULL COMMENT 'SRI',
  `pssi` decimal(20, 2) NULL DEFAULT NULL COMMENT 'PSSI',
  `dr` decimal(20, 2) NULL DEFAULT NULL COMMENT 'DR(%)',
  `rd` decimal(20, 2) NULL DEFAULT NULL COMMENT 'RD(mm)',
  `rd_collect_degree` decimal(20, 2) NULL DEFAULT NULL COMMENT 'RD集度',
  `bilateral_iri` decimal(20, 2) NULL DEFAULT NULL COMMENT '双侧IRI',
  `iri` decimal(20, 2) NULL DEFAULT NULL COMMENT '右侧IRI(m/km)',
  `iri_collect_degree` decimal(20, 2) NULL DEFAULT NULL COMMENT 'IRI集度',
  `mpdl` decimal(20, 2) NULL DEFAULT NULL COMMENT 'MPDL(mm)',
  `mpdc` decimal(20, 2) NULL DEFAULT NULL COMMENT 'MPDC(mm)',
  `mpdr` decimal(20, 2) NULL DEFAULT NULL COMMENT 'MPDR(mm)',
  `mpd_behalf` decimal(20, 2) NULL DEFAULT NULL COMMENT 'MPD代表值(mm)',
  `pbl` int(10) NULL DEFAULT NULL COMMENT 'PBL(个)',
  `pbm` int(10) NULL DEFAULT NULL COMMENT 'PBM(个)',
  `pbh` int(10) NULL DEFAULT NULL COMMENT 'PBH(个)',
  `bilateral_pqi_gp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '双侧轮PQI国标评定',
  `pci_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PCI省厅评定',
  `rdi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT 'RDI省厅评定',
  `bilateral_rqi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '双侧RQI省标评定',
  `bilateral_pqi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '双侧PQI省标评定',
  `rqi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT 'RQI省厅评定',
  `pqi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PQI省厅评定',
  `pwi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PWI省厅评定',
  `pbi_sp` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'PBI省厅评定',
  `bridge_stage_length` int(20) NULL DEFAULT NULL COMMENT '桥梁段长度',
  `tunnel_stage_length` int(20) NULL DEFAULT NULL COMMENT '隧道段长度',
  `management_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '管养单位id',
  `management_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '管养单位名称',
  `legal_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '法人主体单位id',
  `legal_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '法人主体单位名称',
  `data_source` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '数据来源（1 集团检；2 省检）',
  `wr` decimal(10, 2) NULL DEFAULT NULL COMMENT 'WR(%)',
  `disease_repair_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '病害修补率',
  `crack_repair_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '裂缝修补率',
  `crack` decimal(10, 2) NULL DEFAULT NULL COMMENT '龟裂(㎡)',
  `massive_crack` decimal(10, 2) NULL DEFAULT NULL COMMENT '块状裂缝(㎡)',
  `longitudinal_crack` decimal(10, 2) NULL DEFAULT NULL COMMENT '纵裂(㎡)',
  `cross_crack` decimal(10, 2) NULL DEFAULT NULL COMMENT '横裂(㎡)',
  `pit_slot` decimal(10, 2) NULL DEFAULT NULL COMMENT '坑槽(㎡)',
  `loose` decimal(10, 2) NULL DEFAULT NULL COMMENT '松散(㎡)',
  `sink` decimal(10, 2) NULL DEFAULT NULL COMMENT '沉陷(㎡)',
  `rut` decimal(10, 2) NULL DEFAULT NULL COMMENT '车辙(㎡)',
  `wave_bulge` decimal(10, 2) NULL DEFAULT NULL COMMENT '波浪拥包(㎡)',
  `flood_oil` decimal(10, 2) NULL DEFAULT NULL COMMENT '泛油(㎡)',
  `pumping` decimal(10, 2) NULL DEFAULT NULL COMMENT '唧浆(㎡)',
  `massive_repair` decimal(10, 2) NULL DEFAULT NULL COMMENT '块状修补(㎡)',
  `across_repair` decimal(10, 2) NULL DEFAULT NULL COMMENT '横向修补(㎡)',
  `portrait_repair` decimal(10, 2) NULL DEFAULT NULL COMMENT '纵向修补(㎡)',
  `crack_area_subtotal` decimal(10, 2) NULL DEFAULT NULL COMMENT '裂缝类面积小计(㎡)',
  `repair_area_subtotal` decimal(12, 2) NULL DEFAULT NULL COMMENT '修补类面积小计(㎡)',
  `area_total` decimal(12, 2) NULL DEFAULT NULL COMMENT '病害面积总计(㎡)',
  `create_user` bigint(20) NULL DEFAULT NULL COMMENT '创建人',
  `create_dept` bigint(20) NULL DEFAULT NULL COMMENT '创建部门',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_user` bigint(20) NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `status` int(2) NULL DEFAULT NULL COMMENT '状态',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  `crack_area_repair` decimal(10, 2) NULL DEFAULT NULL COMMENT '裂缝修补(㎡)',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `road_idx`(`highway_code`, `highway_segment_simple_name`, `management_unit_id`, `check_year`) USING BTREE,
  INDEX `year_idx`(`check_year`, `data_source`) USING BTREE,
  INDEX `data_source`(`check_year`, `data_source`, `evaluation_unit`, `highway_segment_id`, `management_unit_id`) USING BTREE,
  INDEX `highway_segment_idx`(`highway_segment_id`, `check_year`) USING BTREE,
  INDEX `regular_unit_id`(`regular_unit_id`) USING BTREE,
  INDEX `highway_segment_id`(`highway_segment_id`, `direction`, `roadway`, `end_pile_code`, `start_pile_code`) USING BTREE,
  INDEX `evaluation_unit`(`evaluation_unit`, `data_source`, `is_deleted`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '定检数据' ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `highway_0227_to_li`;
CREATE TABLE `highway_0227_to_li`  (
  `id` bigint(20) NOT NULL COMMENT '路线id',
  `code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线编号',
  `full_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线全称',
  `simple_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线简称',
  `start_pile_code` decimal(8, 3) NULL DEFAULT NULL COMMENT '起点桩号编号(单位:km)',
  `start_pile_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '起点桩号名称',
  `end_pile_code` decimal(8, 3) NULL DEFAULT NULL COMMENT '终点桩号编号(单位:km)',
  `end_pile_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '终点桩号名称',
  `technical_grade` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线技术等级(字典：10 高速公路；11 一级公路；12 二级公路；13 三级公路；14 四级公路；30等外公路)',
  `administrative_grade` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线行政等级(字典：G 国道；S 省道；X 县道；Y 乡道；C 村道；Z 专用公路)',
  `highway_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线类型(字典：0 首都放射线；1 省会放射线；2 北南纵线；3 东西横线；4 地区环线；5 城市绕城环线；6 联络线；7 并行线；8 连接线)',
  `trend` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '走向(字典：0 北；1 东北；2 东；3 东南；4 南；5 西南；6 西；7 西北；8 环形；9 其他)',
  `upward_direction` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '上行方向',
  `downward_direction` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '下行方向',
  `create_user` bigint(20) NULL DEFAULT NULL COMMENT '创建人',
  `create_dept` bigint(20) NULL DEFAULT NULL COMMENT '创建部门',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_user` bigint(20) NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `status` int(2) NULL DEFAULT NULL COMMENT '状态',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '路线数据' ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `highway_segment_0227_to_li`;
CREATE TABLE `highway_segment_0227_to_li`  (
  `id` bigint(20) NOT NULL COMMENT '路段id',
  `management_segment_id` bigint(20) NULL DEFAULT NULL COMMENT '管理路线id',
  `code` varchar(50) CHARACTER SET sjis COLLATE sjis_japanese_ci NULL DEFAULT NULL COMMENT '路段编号',
  `full_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路段全称',
  `simple_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路段简称',
  `highway_id` bigint(20) NULL DEFAULT NULL COMMENT '路线id',
  `highway_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路线编码',
  `region_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '所在政区',
  `region_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '区划代码',
  `start_pile_code` decimal(8, 3) NULL DEFAULT NULL COMMENT '起点桩号编号(单位:km)',
  `start_pile_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '起点桩号名称',
  `center_pile_code` decimal(8, 3) NULL DEFAULT NULL COMMENT '中点桩号编号(单位:km)',
  `end_pile_code` decimal(8, 3) NULL DEFAULT NULL COMMENT '终点桩号编号(单位:km)',
  `end_pile_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '终点桩号名称',
  `start_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '起点名称',
  `end_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '终点名称',
  `upward_direction` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '上行方向',
  `downward_direction` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '下行方向',
  `broken_chain_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '断链类型(字典：1 正常；2 长链；3 短链；4 其他)',
  `mileage` decimal(8, 3) NULL DEFAULT NULL COMMENT '里程(单位:km)',
  `design_speed` decimal(8, 3) NULL DEFAULT NULL COMMENT '设计速度(单位:km/h)',
  `maintenance_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '养护类别(字典：1 一类；2 二类；3 三类)',
  `management_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '管养单位id',
  `management_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '管养单位名称',
  `legal_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '法人单位id',
  `legal_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '法人单位名称',
  `company_segment_id` bigint(20) NULL DEFAULT NULL COMMENT '公司级管理段id',
  `company_segment_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '公司级管理段名称',
  `center_segment_id` bigint(20) NULL DEFAULT NULL COMMENT '中心级管理段id',
  `center_segment_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '中心级管理段名称',
  `cost_benchmarking` float NULL DEFAULT NULL COMMENT '成本对标',
  `standard_mileage` decimal(8, 3) NULL DEFAULT NULL COMMENT '养护标准里程',
  `create_user` bigint(20) NULL DEFAULT NULL COMMENT '创建人',
  `create_dept` bigint(20) NULL DEFAULT NULL COMMENT '创建部门',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_user` bigint(20) NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `status` int(2) NULL DEFAULT NULL COMMENT '状态',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '路段数据' ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `management_unit_0227_to_li`;
CREATE TABLE `management_unit_0227_to_li`  (
  `id` bigint(20) NOT NULL,
  `parent_id` bigint(64) NULL DEFAULT 0 COMMENT '父主键',
  `ancestors` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '祖级列表',
  `management_unit_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '部门名',
  `full_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '部门全称',
  `sort` int(11) NULL DEFAULT NULL COMMENT '排序',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `regular_contract_0227_to_li`;
CREATE TABLE `regular_contract_0227_to_li`  (
  `id` bigint(20) NOT NULL COMMENT '路面定检合同id',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同名称',
  `code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同编号',
  `project_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目名称',
  `check_year` int(11) NULL DEFAULT NULL COMMENT '所属年度',
  `check_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '检测类型（字典：1 集团检；2 省检）',
  `contract_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同状态（字典：0 未完成；1 已完成）',
  `contract_amount` decimal(12, 4) NULL DEFAULT NULL COMMENT '合同额',
  `start_time` date NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` date NULL DEFAULT NULL COMMENT '结束时间',
  `check_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '检测单位id',
  `check_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '检测单位名称',
  `create_user` bigint(20) NULL DEFAULT NULL COMMENT '创建人',
  `create_dept` bigint(20) NULL DEFAULT NULL COMMENT '创建部门',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_user` bigint(20) NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `status` int(2) NULL DEFAULT NULL COMMENT '状态',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '路面定检合同表' ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `regular_unit_0227_to_li`;
CREATE TABLE `regular_unit_0227_to_li`  (
  `id` bigint(64) NOT NULL COMMENT '路面定检id',
  `contract_id` bigint(64) NULL DEFAULT NULL COMMENT '合同id',
  `highway_segment_id` bigint(64) NOT NULL COMMENT '路段id',
  `highway_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '路线编码',
  `highway_segment_simple_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '路段简称',
  `check_year` date NULL DEFAULT NULL COMMENT '检测日期',
  `bilateral_pqi` decimal(10, 2) NULL DEFAULT NULL COMMENT '双侧轮PQI',
  `pqi` decimal(10, 2) NULL DEFAULT NULL COMMENT '右侧轮PQI',
  `pci` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PCI',
  `rdi` decimal(10, 2) NULL DEFAULT NULL COMMENT 'RDI\r\n',
  `bilateral_rqi` decimal(10, 2) NULL DEFAULT NULL COMMENT '双侧RQI',
  `rqi` decimal(10, 2) NULL DEFAULT NULL COMMENT '右侧RQI',
  `pbi` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PBI',
  `pwi` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PWI',
  `sri` decimal(10, 2) NULL DEFAULT NULL COMMENT 'SRI',
  `pssi` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PSSI',
  `check_length` int(20) NULL DEFAULT NULL COMMENT '单元长度',
  `data_source` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '数据来源',
  `bilateral_pqi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT '双侧轮PQI优等路率',
  `right_pqi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT '右侧轮PQI优等路率',
  `pci_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PCI优等路率',
  `rdi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT 'RDI优等路率',
  `bilateral_rqi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT '双侧轮RQI优等路率',
  `right_rqi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT '右侧轮RQI优等路率',
  `pbi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PBI优等路率',
  `pwi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PWI优等路率',
  `sri_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT 'SRI优等路率',
  `pssi_excellent` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PSSI优等路率',
  `whole_bilateral_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '全指标（双侧RQI）达标率',
  `whole_right_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '全指标（右侧RQI）达标率',
  `pci_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT 'PCI达标率',
  `rdi_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT 'RDI达标率',
  `bilateral_pqi_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '双侧PQI达标率',
  `bilateral_rqi_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '双侧RQI达标率',
  `right_rqi_compliance_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '右侧RQI达标率',
  `rdi_hundred_metre` decimal(10, 2) NULL DEFAULT NULL COMMENT '百米RDI≥90占比',
  `disease_scale` decimal(10, 2) NULL DEFAULT NULL COMMENT '病害规模（单位平方米/车道公里）',
  `crack_scale` decimal(10, 2) NULL DEFAULT NULL COMMENT '裂缝规模（单位平方米/车道公里）',
  `disease_repair_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '病害修补率',
  `crack_repair_rate` decimal(10, 2) NULL DEFAULT NULL COMMENT '裂缝修补率',
  `cracking_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '龟裂面积',
  `block_crack_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '块状裂缝面积',
  `portrait_crack_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '纵向裂缝面积',
  `across_crack_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '横向裂缝面积',
  `pit_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '坑槽面积',
  `loose_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '松散面积',
  `settlement_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '沉陷面积',
  `car_withdrawal` decimal(10, 2) NULL DEFAULT NULL COMMENT '车撤面积',
  `wave_embracing_bag_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '波浪拥包面积',
  `oil_flashing_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '泛油面积',
  `pumping_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '唧浆面积',
  `block_crack_repair_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '块状裂缝修补面积',
  `across_crack_repair_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '横向裂缝修补面积',
  `portrait_crack_repair_area` decimal(10, 2) NULL DEFAULT NULL COMMENT '纵向裂缝修补面积',
  `crack_area_subtotal` decimal(10, 2) NULL DEFAULT NULL COMMENT '裂缝类面积小计',
  `deformation_area_subtotal` decimal(10, 2) NULL DEFAULT NULL COMMENT '变形类面积小计',
  `loose_area_subtotal` decimal(10, 2) NULL DEFAULT NULL COMMENT '松散类面积小计',
  `other_area_subtotal` decimal(10, 2) NULL DEFAULT NULL COMMENT '其他类面积小计',
  `disease_area_total` decimal(10, 2) NULL DEFAULT NULL COMMENT '病害面积总计',
  `management_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '管养单位id',
  `management_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '管养单位名称',
  `legal_unit_id` bigint(20) NULL DEFAULT NULL COMMENT '法人单位id',
  `legal_unit_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '法人单位名称',
  `create_user` bigint(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_dept` bigint(64) NULL DEFAULT NULL COMMENT '创建部门',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_user` bigint(64) NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `status` int(2) NULL DEFAULT NULL COMMENT '状态',
  `is_deleted` int(2) NULL DEFAULT 0 COMMENT '是否已删除',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '路面定检评定表' ROW_FORMAT = Dynamic;
"""